# Generated by Django 4.1.6 on 2023-02-07 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.TextField(max_length=11)),
                ('portfolio', models.TextField(blank=True, max_length=100, null=True)),
                ('linkedin', models.TextField(blank=True, max_length=100, null=True)),
                ('github', models.TextField(blank=True, max_length=100, null=True)),
                ('twitter', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Edu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('SSC', 'SSC'), ('HSC', 'HSC'), ('BSC', 'BSC')], max_length=5)),
                ('institution', models.CharField(blank=True, max_length=50, null=True)),
                ('passingyear', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j_title', models.TextField(max_length=30)),
                ('c_name', models.TextField(max_length=30)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('des', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_name', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_name', models.CharField(max_length=20)),
                ('fluency', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=30)),
                ('des', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=30)),
                ('proficiency', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='user/')),
                ('carrier_profile', models.TextField(blank=True, max_length=255, null=True)),
                ('contacts', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.contact')),
                ('edus', models.ManyToManyField(to='app.edu')),
                ('experiences', models.ManyToManyField(to='app.experience')),
                ('interests', models.ManyToManyField(to='app.interest')),
                ('languages', models.ManyToManyField(to='app.language')),
                ('projects', models.ManyToManyField(to='app.project')),
                ('skills', models.ManyToManyField(to='app.skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
