# Generated by Django 4.1.6 on 2023-02-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_contact_user_remove_edu_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edu',
            name='gpa',
        ),
        migrations.AddField(
            model_name='edu',
            name='passingyear',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
