# Generated by Django 4.1.6 on 2023-02-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_edu_gpa_edu_passingyear'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='portfoliosite',
            new_name='portfolio',
        ),
        migrations.RenameField(
            model_name='interest',
            old_name='name',
            new_name='i_name',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='name',
            new_name='l_name',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='location',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='start_date',
        ),
        migrations.AddField(
            model_name='experience',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
