# Generated by Django 4.1.6 on 2023-02-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_portfoliosite_contact_portfolio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='fluency',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
